micronaut:
  application:
    name: droidconmicroservice
  http:
    client:
      log-level:
      read-timeout: 5s
    services:
      users:
        url: https://example.com
        read-timeout: 10s
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/droidcon?currentSchema=droidcon
    username: droidcon
    password: droidcon
    driver-class-name: org.postgresql.Driver
    dialect: POSTGRES
flyway:
  datasources:
    default:
      locations: classpath:dbmigrations
      baseline-on-migrate: true
jpa:
  default:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: validate
    packages-to-scan:
      - 'com.geekmk.droidcon.entity.local'